site_name: Nana's Notebook
site_url: https://zzhzju.github.io/
site_dir: "./site"
site_author: Nana
site_description: >- # 项目描述
  Welcome to Nana's Notebook~

# 代码仓库信息
repo_name: Nana's Notebook # 仓库名称
repo_url: https://github.com/ZZHZJU/ZZHZJU.github.io # 仓库地址
copyright: Copyright &copy; 2024 ~ now |   Nana
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default # 日间模式
    primary: blue
    accent: indigo # 链接等可交互元件的高亮色
    toggle:
      icon: material/weather-sunny # 图标
      name: 切换至夜间模式 # 鼠标悬浮提示
  - media: "(prefers-color-scheme: dark)"
    scheme: slate # 默认夜间模式
    primary: black 
    accent: indigo
    toggle:
      icon: material/weather-night
      name: 切换至日间模式 # 鼠标悬浮提示
  features:
    - navigation.instant   #- header.autohide  #自动隐藏
    #- announce.dismiss   #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking   #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs   #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky    #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections   #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top   # 返回顶部的按钮 在上滑时出现
    - search.suggest   # 搜索输入一些字母时推荐补全整个单词
    - search.highlight   # 搜索出的文章关键词加入高亮
    - navigation.expand   # 打开Tab时左侧目录全部展开
    #- navigation.indexes   #启用节索引页后，可以将文档直接附加到节
    - search.share   #搜索分享按钮
    - content.code.copy   #增添便捷的复制代码交互
    - content.code.annotate   #代码块内注释
    - content.tabs.link   #嵌套表格
plugins:
  - search
  - statistics
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true     #latex数学公式支持
  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js